"""add crud spec fields: esg_categories, org_settings, points_ledger, simulator_scenarios, employee/badge/reward/activity/notification fields, challenge status to string

Revision ID: 4b69155708a7
Revises: 2889ccb7a68e
Create Date: 2026-07-12 16:33:25.759755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b69155708a7'
down_revision: Union[str, Sequence[str], None] = '2889ccb7a68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esg_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('module', sa.Enum('ENVIRONMENTAL', 'SOCIAL', 'GOVERNANCE', name='esgmodule'), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_settings',
    sa.Column('auto_emission', sa.Boolean(), nullable=True),
    sa.Column('require_evidence', sa.Boolean(), nullable=True),
    sa.Column('auto_award_badges', sa.Boolean(), nullable=True),
    sa.Column('email_compliance', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulator_scenarios',
    sa.Column('preset_id', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points_ledger',
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('ref_type', sa.String(), nullable=True),
    sa.Column('ref_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('badges', sa.Column('rarity', sa.String(), nullable=True))
    op.execute("UPDATE challenges SET status = 'UPCOMING' WHERE status IS NULL")
    op.alter_column('challenges', 'status',
               existing_type=postgresql.ENUM('UPCOMING', 'ACTIVE', 'COMPLETED', name='challengestatus'),
               type_=sa.String(),
               nullable=False,
               postgresql_using='status::text')
    op.add_column('csr_activities', sa.Column('emoji', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('notif_weekly_digest', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('notif_email_compliance', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('notif_deadline_alerts', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('notif_activity', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('notif_challenge_reminders', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('notif_goal', sa.Boolean(), nullable=True))
    op.add_column('notifications', sa.Column('title', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('page', sa.String(), nullable=True))
    op.add_column('rewards', sa.Column('category', sa.String(), nullable=True))
    op.add_column('rewards', sa.Column('emoji', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'emoji')
    op.drop_column('rewards', 'category')
    op.drop_column('notifications', 'page')
    op.drop_column('notifications', 'title')
    op.drop_column('employees', 'notif_goal')
    op.drop_column('employees', 'notif_challenge_reminders')
    op.drop_column('employees', 'notif_activity')
    op.drop_column('employees', 'notif_deadline_alerts')
    op.drop_column('employees', 'notif_email_compliance')
    op.drop_column('employees', 'notif_weekly_digest')
    op.drop_column('employees', 'points')
    op.drop_column('employees', 'gender')
    op.drop_column('employees', 'avatar_url')
    op.drop_column('employees', 'password_hash')
    op.drop_column('csr_activities', 'emoji')
    op.alter_column('challenges', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('UPCOMING', 'ACTIVE', 'COMPLETED', name='challengestatus'),
               nullable=True)
    op.drop_column('badges', 'rarity')
    op.drop_table('points_ledger')
    op.drop_table('simulator_scenarios')
    op.drop_table('org_settings')
    op.drop_table('esg_categories')
    # ### end Alembic commands ###
