"""add esg_policies.updated_at

Revision ID: a2fb0776ad83
Revises: 4b69155708a7
Create Date: 2026-07-12 16:37:10.279639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2fb0776ad83'
down_revision: Union[str, Sequence[str], None] = '4b69155708a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('esg_policies', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('esg_policies', 'updated_at')
    # ### end Alembic commands ###
