-- Data for departments
INSERT INTO departments (department_id, name, code, status) VALUES (1, 'Engineering', 'ENG', 'Active');
INSERT INTO departments (department_id, name, code, status) VALUES (2, 'Manufacturing', 'MFG', 'Active');
INSERT INTO departments (department_id, name, code, status) VALUES (3, 'Logistics', 'LOG', 'Active');
INSERT INTO departments (department_id, name, code, status) VALUES (4, 'HR', 'HR', 'Active');
INSERT INTO departments (department_id, name, code, status) VALUES (5, 'Procurement', 'PROC', 'Active');
INSERT INTO departments (department_id, name, code, status) VALUES (6, 'Sales', 'SAL', 'Active');
INSERT INTO departments (department_id, name, code, status) VALUES (7, 'Finance', 'FIN', 'Active');
INSERT INTO departments (department_id, name, code, status) VALUES (8, 'Operations', 'OPS', 'Active');

-- Data for users
INSERT INTO users (user_id, name, role, department, email, status) VALUES (1, 'Alla Harshit Reddy', 'Employee', 'Procurement', 'alla.harshit.reddy@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (2, 'Casey Davis', 'Employee', 'Logistics', 'casey.davis@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (3, 'Taylor Thomas', 'Employee', 'Manufacturing', 'taylor.thomas@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (4, 'Noah Taylor', 'Employee', 'Engineering', 'noah.taylor@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (5, 'Alex Johnson', 'Employee', 'HR', 'alex.johnson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (6, 'Casey Thomas', 'Employee', 'Engineering', 'casey.thomas@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (7, 'Ethan Davis', 'Employee', 'Finance', 'ethan.davis@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (8, 'Casey Anderson', 'Employee', 'Procurement', 'casey.anderson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (9, 'Alex Brown', 'Employee', 'Finance', 'alex.brown@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (10, 'Harshit Wilson', 'Employee', 'Logistics', 'harshit.wilson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (11, 'Jamie Moore', 'Employee', 'Manufacturing', 'jamie.moore@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (12, 'Jordan Taylor', 'Employee', 'Manufacturing', 'jordan.taylor@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (13, 'Sarah Moore', 'Employee', 'Procurement', 'sarah.moore@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (14, 'Sam Anderson', 'Employee', 'Manufacturing', 'sam.anderson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (15, 'Emma Johnson', 'Employee', 'Procurement', 'emma.johnson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (16, 'Mia Moore', 'Employee', 'HR', 'mia.moore@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (17, 'Jordan Smith', 'Employee', 'HR', 'jordan.smith@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (18, 'Avery Johnson', 'Employee', 'HR', 'avery.johnson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (19, 'Taylor Taylor', 'Employee', 'Procurement', 'taylor.taylor@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (20, 'Liam Moore', 'Employee', 'Logistics', 'liam.moore@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (21, 'Sarah Moore', 'Employee', 'HR', 'sarah.moore@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (22, 'Riley Johnson', 'Employee', 'Logistics', 'riley.johnson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (23, 'Ethan Davis', 'Employee', 'Logistics', 'ethan.davis@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (24, 'Liam Taylor', 'Employee', 'Procurement', 'liam.taylor@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (25, 'Ethan Davis', 'Employee', 'Sales', 'ethan.davis@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (26, 'Sam Davis', 'Employee', 'Engineering', 'sam.davis@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (27, 'Harshit Taylor', 'Employee', 'Procurement', 'harshit.taylor@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (28, 'Jordan Davis', 'Employee', 'Sales', 'jordan.davis@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (29, 'Jamie Anderson', 'Employee', 'Finance', 'jamie.anderson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (30, 'Liam Brown', 'Employee', 'Procurement', 'liam.brown@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (31, 'Chris Davis', 'Employee', 'Procurement', 'chris.davis@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (32, 'Noah Taylor', 'Employee', 'Finance', 'noah.taylor@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (33, 'Sarah Davis', 'Employee', 'Logistics', 'sarah.davis@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (34, 'James Anderson', 'Employee', 'Manufacturing', 'james.anderson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (35, 'Sam Johnson', 'Employee', 'Logistics', 'sam.johnson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (36, 'Morgan Taylor', 'Employee', 'Manufacturing', 'morgan.taylor@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (37, 'Emma Taylor', 'Employee', 'Operations', 'emma.taylor@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (38, 'James Wilson', 'Employee', 'Engineering', 'james.wilson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (39, 'Taylor Thomas', 'Employee', 'Procurement', 'taylor.thomas@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (40, 'Harshit Johnson', 'Employee', 'Procurement', 'harshit.johnson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (41, 'Olivia Brown', 'Employee', 'Operations', 'olivia.brown@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (42, 'Alex Wilson', 'Employee', 'Logistics', 'alex.wilson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (43, 'James Johnson', 'Employee', 'Procurement', 'james.johnson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (44, 'James Martin', 'Employee', 'HR', 'james.martin@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (45, 'Chris Moore', 'Employee', 'Logistics', 'chris.moore@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (46, 'Ethan Thomas', 'Manager', 'Engineering', 'ethan.thomas@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (47, 'Mia Moore', 'Manager', 'Operations', 'mia.moore@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (48, 'Alex Johnson', 'Manager', 'Sales', 'alex.johnson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (49, 'Avery Davis', 'Manager', 'Engineering', 'avery.davis@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (50, 'Casey Martin', 'Manager', 'Manufacturing', 'casey.martin@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (51, 'Jordan Anderson', 'Manager', 'Manufacturing', 'jordan.anderson@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (52, 'Ethan Brown', 'Manager', 'Logistics', 'ethan.brown@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (53, 'Sophia Thomas', 'Manager', 'Logistics', 'sophia.thomas@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (54, 'Riley Thomas', 'ESG Manager', 'Finance', 'riley.thomas@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (55, 'Jamie Thomas', 'ESG Manager', 'HR', 'jamie.thomas@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (56, 'Avery Taylor', 'ESG Manager', 'Sales', 'avery.taylor@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (57, 'Liam Thomas', 'ESG Manager', 'Operations', 'liam.thomas@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (58, 'Taylor Davis', 'Admin', 'HR', 'taylor.davis@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (59, 'Jordan Moore', 'Admin', 'Engineering', 'jordan.moore@ecosphere.com', 'Active');
INSERT INTO users (user_id, name, role, department, email, status) VALUES (60, 'Noah Thomas', 'Admin', 'HR', 'noah.thomas@ecosphere.com', 'Active');

-- Data for badges
INSERT INTO badges (badge_id, badge) VALUES (1, 'Eco Warrior');
INSERT INTO badges (badge_id, badge) VALUES (2, 'CSR Champion');
INSERT INTO badges (badge_id, badge) VALUES (3, 'Carbon Saver');
INSERT INTO badges (badge_id, badge) VALUES (4, 'Green Coder');
INSERT INTO badges (badge_id, badge) VALUES (5, 'Tree Guardian');
INSERT INTO badges (badge_id, badge) VALUES (6, 'Water Protector');
INSERT INTO badges (badge_id, badge) VALUES (7, 'Compliance Expert');
INSERT INTO badges (badge_id, badge) VALUES (8, 'Recycling Master');
INSERT INTO badges (badge_id, badge) VALUES (9, 'Community Builder');
INSERT INTO badges (badge_id, badge) VALUES (10, 'Sustainability Hero');
INSERT INTO badges (badge_id, badge) VALUES (11, 'Energy Saver');
INSERT INTO badges (badge_id, badge) VALUES (12, 'Climate Leader');

-- Data for csr_activities
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (1, 'Tree Plantation Drive', 'Environment', 'Manufacturing', 'Location 1', '2026-08-08', '33', '100', 30, 'Upcoming');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (2, 'Beach Cleanup', 'Community', 'HR', 'Location 2', '2026-10-22', '9', '50', 75, 'Upcoming');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (3, 'Blood Donation Camp', 'Recycling', 'Operations', 'Location 3', '2026-09-26', '21', '100', 75, 'Ongoing');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (4, 'E-Waste Collection', 'Environment', 'Finance', 'Location 4', '2026-10-14', '11', '40', 75, 'Ongoing');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (5, 'Plastic-Free Campus', 'Recycling', 'Manufacturing', 'Location 5', '2026-08-13', '26', '30', 50, 'Upcoming');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (6, 'Water Workshop', 'CSR', 'Operations', 'Location 6', '2026-09-14', '17', '40', 40, 'Ongoing');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (7, 'Food Drive', 'Environment', 'Operations', 'Location 7', '2026-12-04', '36', '75', 30, 'Completed');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (8, 'Green Office', 'Environment', 'HR', 'Location 8', '2026-09-14', '6', '100', 75, 'Ongoing');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (9, 'Cycle to Work', 'Environment', 'Logistics', 'Location 9', '2026-11-01', '30', '40', 75, 'Ongoing');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (10, 'Lake Cleanup', 'Training', 'Operations', 'Location 10', '2026-09-07', '41', '75', 50, 'Upcoming');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (11, 'Solar Awareness', 'Recycling', 'Engineering', 'Location 11', '2026-10-02', '23', '30', 30, 'Completed');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (12, 'Paperless Week', 'Community', 'Logistics', 'Location 12', '2026-08-17', '69', '75', 30, 'Upcoming');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (13, 'Skill Training', 'Environment', 'HR', 'Location 13', '2026-11-04', '24', '30', 100, 'Upcoming');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (14, 'Recycling Marathon', 'Environment', 'Manufacturing', 'Location 14', '2026-11-22', '81', '100', 100, 'Completed');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (15, 'Compost Workshop', 'Health', 'HR', 'Location 15', '2026-10-08', '45', '100', 50, 'Ongoing');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (16, 'School Outreach', 'Training', 'Sales', 'Location 16', '2026-08-01', '24', '40', 75, 'Completed');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (17, 'Health Camp', 'Environment', 'HR', 'Location 17', '2026-12-09', '17', '100', 40, 'Ongoing');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (18, 'Energy Audit', 'Health', 'Procurement', 'Location 18', '2026-09-15', '12', '30', 100, 'Completed');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (19, 'Rainwater Campaign', 'Recycling', 'Engineering', 'Location 19', '2026-12-10', '44', '50', 30, 'Upcoming');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (20, 'Eco Fair', 'Environment', 'Logistics', 'Location 20', '2026-10-10', '12', '50', 100, 'Upcoming');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (21, 'CSR Hackday', 'Recycling', 'Procurement', 'Location 21', '2026-12-16', '18', '50', 50, 'Upcoming');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (22, 'Clean Air Walk', 'Training', 'Procurement', 'Location 22', '2026-08-01', '25', '30', 50, 'Upcoming');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (23, 'River Cleanup', 'Recycling', 'Operations', 'Location 23', '2026-12-23', '15', '50', 75, 'Completed');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (24, 'Green Coding', 'Environment', 'Logistics', 'Location 24', '2026-12-02', '8', '30', 50, 'Completed');
INSERT INTO csr_activities (activity_id, title, category, department, location, date, participants, capacity, points, status) VALUES (25, 'Community Garden', 'Training', 'Logistics', 'Location 25', '2026-08-10', '23', '100', 50, 'Upcoming');

-- Data for challenges
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (1, 'Zero Plastic', 200, 'Hard', 'Draft');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (2, 'Cycle Challenge', 100, 'Medium', 'Draft');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (3, 'Green Coding', 100, 'Hard', 'Draft');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (4, 'Paperless Week', 100, 'Hard', 'Draft');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (5, 'Carpool Month', 200, 'Easy', 'Draft');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (6, 'Energy Saver', 150, 'Easy', 'Completed');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (7, 'Water Saver', 100, 'Medium', 'Draft');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (8, 'Waste Warrior', 100, 'Hard', 'Active');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (9, 'Eco Quiz', 100, 'Easy', 'Completed');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (10, 'Plant 10 Trees', 100, 'Easy', 'Draft');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (11, 'Reusable Bottle', 150, 'Easy', 'Completed');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (12, 'LED Switch', 150, 'Easy', 'Draft');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (13, 'Public Transport', 150, 'Easy', 'Draft');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (14, 'Office Cleanup', 200, 'Medium', 'Completed');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (15, 'Earth Hour', 100, 'Hard', 'Draft');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (16, 'Carbon Cut', 150, 'Medium', 'Active');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (17, 'Green Commute', 200, 'Hard', 'Draft');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (18, 'Recycle Hero', 150, 'Hard', 'Draft');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (19, 'Clean Desk', 200, 'Easy', 'Completed');
INSERT INTO challenges (challenge_id, title, xp, difficulty, status) VALUES (20, 'Sustainability Sprint', 200, 'Hard', 'Active');

-- Data for participations
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('1', 58, 12, 'Pending', '100', '2026-09-22');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('2', 7, 12, 'Rejected', '50', '2026-12-24');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('3', 10, 8, 'Pending', '30', '2026-11-01');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('4', 12, 24, 'Approved', '50', '2026-09-09');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('5', 11, 23, 'Pending', '50', '2026-08-28');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('6', 31, 8, 'Pending', '50', '2026-10-10');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('7', 53, 8, 'Pending', '0', '2026-09-13');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('8', 22, 9, 'Pending', '40', '2026-10-21');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('9', 33, 13, 'Rejected', '75', '2026-10-01');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('10', 8, 9, 'Pending', '75', '2026-10-02');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('11', 7, 20, 'Approved', '40', '2026-10-14');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('12', 39, 17, 'Pending', '50', '2026-12-07');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('13', 17, 2, 'Rejected', '50', '2026-08-17');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('14', 60, 18, 'Rejected', '100', '2026-09-12');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('15', 28, 3, 'Rejected', '40', '2026-12-11');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('16', 43, 4, 'Rejected', '40', '2026-12-10');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('17', 43, 14, 'Approved', '50', '2026-10-18');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('18', 9, 7, 'Approved', '100', '2026-11-22');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('19', 48, 6, 'Rejected', '75', '2026-10-13');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('20', 36, 1, 'Approved', '40', '2026-09-14');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('21', 51, 19, 'Rejected', '100', '2026-10-15');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('22', 29, 15, 'Rejected', '30', '2026-12-16');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('23', 51, 24, 'Pending', '100', '2026-08-10');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('24', 33, 22, 'Rejected', '75', '2026-10-03');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('25', 53, 25, 'Pending', '100', '2026-10-08');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('26', 52, 7, 'Pending', '0', '2026-08-08');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('27', 31, 20, 'Pending', '50', '2026-11-21');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('28', 37, 7, 'Rejected', '100', '2026-11-16');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('29', 26, 8, 'Pending', '100', '2026-08-25');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('30', 56, 25, 'Pending', '50', '2026-09-06');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('31', 52, 23, 'Rejected', '50', '2026-08-18');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('32', 16, 4, 'Approved', '30', '2026-11-22');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('33', 34, 18, 'Rejected', '40', '2026-11-20');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('34', 53, 24, 'Rejected', '50', '2026-12-15');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('35', 58, 6, 'Rejected', '50', '2026-11-09');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('36', 49, 8, 'Rejected', '40', '2026-12-16');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('37', 41, 8, 'Approved', '50', '2026-08-23');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('38', 19, 8, 'Approved', '40', '2026-10-18');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('39', 6, 5, 'Pending', '30', '2026-11-23');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('40', 10, 23, 'Pending', '0', '2026-11-14');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('41', 22, 18, 'Approved', '50', '2026-08-07');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('42', 54, 14, 'Approved', '75', '2026-08-28');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('43', 57, 25, 'Rejected', '50', '2026-11-01');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('44', 23, 10, 'Approved', '50', '2026-12-24');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('45', 48, 18, 'Rejected', '30', '2026-11-08');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('46', 18, 14, 'Approved', '0', '2026-11-11');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('47', 43, 22, 'Approved', '100', '2026-09-27');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('48', 30, 5, 'Rejected', '75', '2026-08-13');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('49', 38, 19, 'Rejected', '0', '2026-08-21');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('50', 28, 5, 'Approved', '30', '2026-08-09');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('51', 25, 11, 'Pending', '50', '2026-10-11');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('52', 49, 13, 'Approved', '50', '2026-10-27');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('53', 6, 16, 'Pending', '100', '2026-12-02');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('54', 23, 8, 'Rejected', '0', '2026-08-25');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('55', 2, 8, 'Pending', '0', '2026-12-05');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('56', 16, 5, 'Approved', '100', '2026-08-19');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('57', 14, 15, 'Rejected', '40', '2026-10-06');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('58', 39, 20, 'Rejected', '100', '2026-08-25');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('59', 53, 6, 'Approved', '0', '2026-12-01');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('60', 60, 10, 'Rejected', '100', '2026-11-13');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('61', 46, 7, 'Pending', '75', '2026-09-04');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('62', 45, 25, 'Approved', '100', '2026-12-26');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('63', 8, 19, 'Pending', '40', '2026-12-14');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('64', 43, 12, 'Pending', '75', '2026-10-01');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('65', 55, 14, 'Approved', '0', '2026-11-12');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('66', 41, 15, 'Rejected', '30', '2026-11-06');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('67', 47, 17, 'Rejected', '40', '2026-12-26');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('68', 59, 18, 'Approved', '50', '2026-11-27');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('69', 47, 19, 'Approved', '40', '2026-09-27');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('70', 60, 3, 'Approved', '50', '2026-09-25');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('71', 30, 19, 'Rejected', '100', '2026-11-11');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('72', 2, 16, 'Approved', '30', '2026-11-07');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('73', 23, 9, 'Approved', '40', '2026-12-23');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('74', 57, 9, 'Rejected', '0', '2026-12-07');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('75', 6, 8, 'Rejected', '50', '2026-11-18');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('76', 49, 8, 'Rejected', '50', '2026-11-15');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('77', 51, 1, 'Pending', '40', '2026-09-13');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('78', 45, 8, 'Approved', '100', '2026-12-12');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('79', 31, 18, 'Rejected', '40', '2026-11-24');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('80', 36, 11, 'Approved', '100', '2026-11-09');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('81', 20, 9, 'Pending', '0', '2026-09-11');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('82', 8, 24, 'Rejected', '100', '2026-09-07');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('83', 14, 24, 'Approved', '40', '2026-12-25');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('84', 34, 20, 'Approved', '0', '2026-09-10');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('85', 15, 12, 'Pending', '40', '2026-08-23');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('86', 35, 5, 'Approved', '0', '2026-08-18');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('87', 19, 23, 'Pending', '100', '2026-11-04');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('88', 56, 1, 'Rejected', '40', '2026-11-16');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('89', 29, 11, 'Pending', '0', '2026-10-28');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('90', 31, 4, 'Pending', '50', '2026-11-03');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('91', 37, 21, 'Rejected', '0', '2026-09-05');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('92', 52, 19, 'Approved', '0', '2026-09-04');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('93', 36, 25, 'Approved', '75', '2026-12-26');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('94', 40, 8, 'Rejected', '50', '2026-11-15');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('95', 20, 19, 'Approved', '40', '2026-12-20');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('96', 4, 20, 'Rejected', '0', '2026-09-21');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('97', 14, 9, 'Rejected', '0', '2026-09-08');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('98', 12, 18, 'Pending', '30', '2026-08-14');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('99', 29, 23, 'Rejected', '50', '2026-10-02');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('100', 15, 10, 'Rejected', '40', '2026-11-03');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('101', 44, 8, 'Approved', '100', '2026-12-22');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('102', 52, 7, 'Approved', '0', '2026-12-08');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('103', 42, 5, 'Approved', '30', '2026-08-02');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('104', 11, 10, 'Rejected', '100', '2026-12-10');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('105', 29, 4, 'Approved', '100', '2026-10-23');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('106', 26, 9, 'Rejected', '75', '2026-11-15');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('107', 6, 20, 'Pending', '50', '2026-10-20');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('108', 17, 1, 'Pending', '30', '2026-12-19');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('109', 2, 25, 'Rejected', '40', '2026-12-02');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('110', 49, 25, 'Pending', '50', '2026-12-21');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('111', 29, 9, 'Pending', '75', '2026-11-21');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('112', 53, 16, 'Pending', '50', '2026-10-14');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('113', 22, 11, 'Rejected', '0', '2026-09-11');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('114', 27, 23, 'Approved', '40', '2026-11-27');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('115', 49, 18, 'Pending', '50', '2026-08-11');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('116', 17, 11, 'Pending', '50', '2026-12-27');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('117', 1, 22, 'Rejected', '50', '2026-11-02');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('118', 13, 17, 'Approved', '75', '2026-11-21');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('119', 29, 25, 'Pending', '30', '2026-10-18');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('120', 9, 10, 'Approved', '100', '2026-11-04');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('121', 2, 21, 'Rejected', '30', '2026-09-10');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('122', 36, 1, 'Rejected', '50', '2026-08-08');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('123', 54, 4, 'Approved', '0', '2026-09-16');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('124', 60, 23, 'Approved', '75', '2026-10-14');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('125', 54, 16, 'Approved', '30', '2026-11-18');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('126', 10, 13, 'Pending', '75', '2026-12-24');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('127', 57, 5, 'Pending', '40', '2026-11-11');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('128', 60, 17, 'Approved', '0', '2026-10-24');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('129', 20, 19, 'Rejected', '100', '2026-11-28');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('130', 10, 15, 'Rejected', '50', '2026-10-11');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('131', 36, 25, 'Rejected', '50', '2026-11-11');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('132', 56, 7, 'Rejected', '30', '2026-12-13');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('133', 15, 25, 'Approved', '0', '2026-10-24');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('134', 31, 23, 'Approved', '50', '2026-09-16');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('135', 3, 5, 'Rejected', '75', '2026-10-28');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('136', 7, 15, 'Pending', '75', '2026-11-01');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('137', 47, 5, 'Approved', '100', '2026-09-03');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('138', 31, 9, 'Approved', '75', '2026-11-21');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('139', 6, 11, 'Rejected', '75', '2026-11-11');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('140', 41, 23, 'Approved', '75', '2026-08-20');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('141', 5, 8, 'Rejected', '100', '2026-10-08');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('142', 48, 3, 'Approved', '0', '2026-08-15');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('143', 11, 23, 'Approved', '0', '2026-08-11');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('144', 51, 2, 'Approved', '40', '2026-10-14');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('145', 10, 8, 'Rejected', '50', '2026-12-22');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('146', 51, 6, 'Pending', '30', '2026-08-20');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('147', 56, 13, 'Rejected', '100', '2026-09-16');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('148', 59, 19, 'Pending', '30', '2026-11-21');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('149', 17, 15, 'Approved', '100', '2026-08-26');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('150', 30, 10, 'Rejected', '75', '2026-09-03');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('151', 29, 12, 'Rejected', '40', '2026-11-23');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('152', 17, 15, 'Approved', '30', '2026-11-28');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('153', 31, 4, 'Pending', '50', '2026-12-12');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('154', 37, 10, 'Rejected', '40', '2026-08-27');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('155', 43, 13, 'Approved', '0', '2026-12-28');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('156', 44, 25, 'Rejected', '0', '2026-12-24');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('157', 32, 10, 'Pending', '75', '2026-10-08');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('158', 41, 7, 'Rejected', '40', '2026-09-21');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('159', 7, 21, 'Rejected', '0', '2026-10-26');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('160', 29, 2, 'Rejected', '40', '2026-09-03');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('161', 59, 10, 'Approved', '100', '2026-11-06');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('162', 13, 5, 'Rejected', '40', '2026-12-17');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('163', 59, 9, 'Pending', '40', '2026-11-26');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('164', 19, 24, 'Approved', '0', '2026-11-03');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('165', 10, 25, 'Pending', '100', '2026-11-28');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('166', 52, 18, 'Approved', '0', '2026-11-01');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('167', 17, 18, 'Pending', '50', '2026-10-22');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('168', 48, 22, 'Approved', '75', '2026-11-27');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('169', 41, 12, 'Pending', '100', '2026-09-16');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('170', 2, 20, 'Rejected', '40', '2026-12-08');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('171', 42, 3, 'Rejected', '50', '2026-10-21');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('172', 27, 4, 'Pending', '0', '2026-08-10');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('173', 32, 4, 'Pending', '30', '2026-12-05');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('174', 25, 15, 'Approved', '100', '2026-12-14');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('175', 38, 24, 'Rejected', '30', '2026-11-21');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('176', 7, 16, 'Rejected', '50', '2026-10-02');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('177', 45, 12, 'Pending', '50', '2026-11-08');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('178', 55, 12, 'Pending', '100', '2026-10-18');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('179', 58, 21, 'Approved', '0', '2026-11-09');
INSERT INTO participations (participation_id, user_id, activity_id, approval_status, points_earned, completion_date) VALUES ('180', 13, 4, 'Approved', '0', '2026-09-21');

-- Data for environmental_goals
INSERT INTO environmental_goals (goal_id, goal_name, department, target_reduction_percent, progress_percent, deadline) VALUES ('1', 'Goal 1', 'Operations', '30', '3', '2026-12-31');
INSERT INTO environmental_goals (goal_id, goal_name, department, target_reduction_percent, progress_percent, deadline) VALUES ('2', 'Goal 2', 'Engineering', '25', '51', '2026-12-31');
INSERT INTO environmental_goals (goal_id, goal_name, department, target_reduction_percent, progress_percent, deadline) VALUES ('3', 'Goal 3', 'Finance', '13', '62', '2026-12-31');
INSERT INTO environmental_goals (goal_id, goal_name, department, target_reduction_percent, progress_percent, deadline) VALUES ('4', 'Goal 4', 'Operations', '12', '10', '2026-12-31');
INSERT INTO environmental_goals (goal_id, goal_name, department, target_reduction_percent, progress_percent, deadline) VALUES ('5', 'Goal 5', 'Sales', '29', '18', '2026-12-31');
INSERT INTO environmental_goals (goal_id, goal_name, department, target_reduction_percent, progress_percent, deadline) VALUES ('6', 'Goal 6', 'Manufacturing', '14', '35', '2026-12-31');
INSERT INTO environmental_goals (goal_id, goal_name, department, target_reduction_percent, progress_percent, deadline) VALUES ('7', 'Goal 7', 'Sales', '22', '76', '2026-12-31');
INSERT INTO environmental_goals (goal_id, goal_name, department, target_reduction_percent, progress_percent, deadline) VALUES ('8', 'Goal 8', 'Procurement', '24', '64', '2026-12-31');
INSERT INTO environmental_goals (goal_id, goal_name, department, target_reduction_percent, progress_percent, deadline) VALUES ('9', 'Goal 9', 'Finance', '13', '89', '2026-12-31');
INSERT INTO environmental_goals (goal_id, goal_name, department, target_reduction_percent, progress_percent, deadline) VALUES ('10', 'Goal 10', 'Manufacturing', '30', '83', '2026-12-31');
INSERT INTO environmental_goals (goal_id, goal_name, department, target_reduction_percent, progress_percent, deadline) VALUES ('11', 'Goal 11', 'HR', '23', '57', '2026-12-31');
INSERT INTO environmental_goals (goal_id, goal_name, department, target_reduction_percent, progress_percent, deadline) VALUES ('12', 'Goal 12', 'HR', '23', '43', '2026-12-31');
INSERT INTO environmental_goals (goal_id, goal_name, department, target_reduction_percent, progress_percent, deadline) VALUES ('13', 'Goal 13', 'Operations', '22', '53', '2026-12-31');
INSERT INTO environmental_goals (goal_id, goal_name, department, target_reduction_percent, progress_percent, deadline) VALUES ('14', 'Goal 14', 'Manufacturing', '20', '54', '2026-12-31');
INSERT INTO environmental_goals (goal_id, goal_name, department, target_reduction_percent, progress_percent, deadline) VALUES ('15', 'Goal 15', 'Sales', '18', '47', '2026-12-31');

-- Data for audits
INSERT INTO audits (audit_id, title, department, status) VALUES ('1', 'Audit 1', 'Engineering', 'Under Review');
INSERT INTO audits (audit_id, title, department, status) VALUES ('2', 'Audit 2', 'Sales', 'Completed');
INSERT INTO audits (audit_id, title, department, status) VALUES ('3', 'Audit 3', 'Sales', 'Under Review');
INSERT INTO audits (audit_id, title, department, status) VALUES ('4', 'Audit 4', 'Manufacturing', 'Scheduled');
INSERT INTO audits (audit_id, title, department, status) VALUES ('5', 'Audit 5', 'Engineering', 'Scheduled');
INSERT INTO audits (audit_id, title, department, status) VALUES ('6', 'Audit 6', 'Logistics', 'Completed');
INSERT INTO audits (audit_id, title, department, status) VALUES ('7', 'Audit 7', 'Logistics', 'Under Review');
INSERT INTO audits (audit_id, title, department, status) VALUES ('8', 'Audit 8', 'Sales', 'Under Review');
INSERT INTO audits (audit_id, title, department, status) VALUES ('9', 'Audit 9', 'Procurement', 'Completed');
INSERT INTO audits (audit_id, title, department, status) VALUES ('10', 'Audit 10', 'Manufacturing', 'Under Review');
INSERT INTO audits (audit_id, title, department, status) VALUES ('11', 'Audit 11', 'Sales', 'Scheduled');
INSERT INTO audits (audit_id, title, department, status) VALUES ('12', 'Audit 12', 'Manufacturing', 'Under Review');
INSERT INTO audits (audit_id, title, department, status) VALUES ('13', 'Audit 13', 'Finance', 'Under Review');
INSERT INTO audits (audit_id, title, department, status) VALUES ('14', 'Audit 14', 'Procurement', 'Under Review');
INSERT INTO audits (audit_id, title, department, status) VALUES ('15', 'Audit 15', 'Operations', 'Under Review');
INSERT INTO audits (audit_id, title, department, status) VALUES ('16', 'Audit 16', 'Logistics', 'Scheduled');
INSERT INTO audits (audit_id, title, department, status) VALUES ('17', 'Audit 17', 'Logistics', 'Completed');
INSERT INTO audits (audit_id, title, department, status) VALUES ('18', 'Audit 18', 'Engineering', 'Scheduled');
INSERT INTO audits (audit_id, title, department, status) VALUES ('19', 'Audit 19', 'Manufacturing', 'Under Review');
INSERT INTO audits (audit_id, title, department, status) VALUES ('20', 'Audit 20', 'Operations', 'Completed');

-- Data for compliance_issues
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('1', 'Compliance Issue 1', 'High', 'Operations', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('2', 'Compliance Issue 2', 'High', 'Finance', 'Resolved');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('3', 'Compliance Issue 3', 'High', 'Engineering', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('4', 'Compliance Issue 4', 'Medium', 'Operations', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('5', 'Compliance Issue 5', 'Medium', 'Operations', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('6', 'Compliance Issue 6', 'Low', 'Procurement', 'Resolved');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('7', 'Compliance Issue 7', 'Low', 'HR', 'Resolved');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('8', 'Compliance Issue 8', 'High', 'Manufacturing', 'Resolved');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('9', 'Compliance Issue 9', 'High', 'HR', 'Resolved');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('10', 'Compliance Issue 10', 'Medium', 'Finance', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('11', 'Compliance Issue 11', 'High', 'Engineering', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('12', 'Compliance Issue 12', 'High', 'Logistics', 'Resolved');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('13', 'Compliance Issue 13', 'Medium', 'Logistics', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('14', 'Compliance Issue 14', 'Medium', 'Sales', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('15', 'Compliance Issue 15', 'Medium', 'Procurement', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('16', 'Compliance Issue 16', 'High', 'HR', 'Resolved');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('17', 'Compliance Issue 17', 'Medium', 'HR', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('18', 'Compliance Issue 18', 'Medium', 'Operations', 'Resolved');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('19', 'Compliance Issue 19', 'Low', 'Operations', 'Resolved');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('20', 'Compliance Issue 20', 'Medium', 'Manufacturing', 'Resolved');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('21', 'Compliance Issue 21', 'High', 'Engineering', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('22', 'Compliance Issue 22', 'Medium', 'Finance', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('23', 'Compliance Issue 23', 'High', 'Engineering', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('24', 'Compliance Issue 24', 'High', 'Procurement', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('25', 'Compliance Issue 25', 'High', 'Operations', 'Resolved');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('26', 'Compliance Issue 26', 'Medium', 'Engineering', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('27', 'Compliance Issue 27', 'Medium', 'Sales', 'Resolved');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('28', 'Compliance Issue 28', 'High', 'Sales', 'Resolved');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('29', 'Compliance Issue 29', 'Low', 'Manufacturing', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('30', 'Compliance Issue 30', 'Low', 'Sales', 'Resolved');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('31', 'Compliance Issue 31', 'High', 'Procurement', 'Resolved');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('32', 'Compliance Issue 32', 'High', 'Manufacturing', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('33', 'Compliance Issue 33', 'Low', 'Operations', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('34', 'Compliance Issue 34', 'High', 'Finance', 'Open');
INSERT INTO compliance_issues (issue_id, title, severity, department, status) VALUES ('35', 'Compliance Issue 35', 'Medium', 'HR', 'Open');

